name: Swift

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.10'
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: SwiftLint
      uses: raphaelbussa/swiftlint-action@main
      with:
        subcommand: lint --strict